name: asblackaswhite
favicon: null
layout_spectrum: 0.9592327950522304
typography_spectrum: 0.17690470605157316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#ffffff'
    - '#003a00'
    - '#118e0c'
    - '#0d678a'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
