name: asblackaswhite
favicon: null
layout_spectrum: 0.9592327950522304
typography_spectrum: 0.17690470605157316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8e9397'
    - '#3c3940'
    - '#e4e484'
    - '#e89681'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
